# Generated by Django 5.2.1 on 2025-05-14 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kittiary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
